---
- name: Automate SNOW 
  hosts: localhost
  connection: local    
  vars:
    problem_list: []
  tasks:
    - name: Include variables
      include_vars: main.yml

    - name: Find user created problems
      servicenow.itsm.problem_info:
        instance: "{{ instance }}"
        query:
          - sys_created_by: = {{ incident_caller }}
            active: = true
      register: problems

    - name: Query problem number and creation time 
      set_fact:
        problem_list: '{{ problem_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ problems.records }}"
      when: problems

    - name: Assign problem for assessment
      servicenow.itsm.problem:
        number: "{{ item.number }}"
        state: assess
        assigned_to: "{{ incident_caller }}"
      loop: "{{ problem_list }}"

    - name: Create change request for resolving a problem
      servicenow.itsm.change_request:
        instance: "{{ instance }}"
        state: new
        type: standard
        short_description: "Reboot the webserver"
        description: "Just power off the entire rack to be sure"
        on_hold: true
        hold_reason: "Wait until after board meeting!"
        other:
          parent: "{{ item.number }}"
      loop: "{{ problem_list }}"
      register: change

    # - debug:
    #     msg: "A new change request has been created {{ change.results[0].record.number }}"

    - name: Debug change facts
      debug:
        var: change
        
    - name: Debug change requests
      debug:
        msg: "A new change request has been created {{ item.record.number }}"
      loop: "{{ change.results | list }}"