---
- name: Automate Service Now 
  hosts: localhost
  connection: local    
  vars:
    incident_list: []

  tasks:
    - name: Include variables
      include_vars: main.yml

    - name: Find user created incidents
      servicenow.itsm.incident_info:
        query:
          - sys_created_by: is {{ incident_caller }}
            active: = true
      register: _incidents

    - name: Query incident number and creation time 
      set_fact:
        incident_list: '{{ incident_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ _incidents.records }}"
      when: _incidents

    - name: Create a problem from incident
      servicenow.itsm.problem:
        short_description: "The website is down!"
        description: "{{ incident_caller }} created a new problem"
      register: problem

    - name: Assign a problem to a user for assessment
      servicenow.itsm.problem:
        number: "{{ problem.record.number }}"
        state: assess
        assigned_to: "{{ incident_caller }}"

    - name: Update incident status now that problem has been created
      servicenow.itsm.incident:
        number: "{{ item.number }}"
        state: in_progress
        other:
          problem_id: "{{ problem.record.number }}"
      loop: "{{ incident_list }}"

    - name: Debug problem number
      debug:
        msg: "A new problem has been created: {{ problem.record.number }}"

