---
- name: Automate Service Now 
  hosts: linux
  connection: local
  gather_facts: yes
  vars:
    node_info: []
  tasks:
    - name: Include variables
      include_vars: main.yml

    # - name: Collect Inventory facts
    #   ansible.builtin.set_fact:
    #     node_info: "{{ node_info + [{'hostname': hostvars[item].ansible_hostname, 'default_ip': hostvars[item].ansible_host, 'default_mac': '00:00:00:00:00:00', 'vendor': hostvars[item].ansible_facts['product_name'] }] }}"
    #   loop: "{{ groups['linux'] }}"

    # - name: Create Configuration item
    #   servicenow.itsm.configuration_item:
    #     instance: "{{ instance }}"
    #     name: "{{ item.hostname }}"
    #     ip_address: "{{ item.default_ip }}"
    #     mac_address: "{{ item.default_mac }}"
    #     environment: test
    #     other:
    #       sys_class_name: cmdb_ci_linux_server
    #   loop: "{{ node_info }}"
    #   register: _configuration_item

    - name: Create Configuration item
      servicenow.itsm.configuration_item:
        instance: "{{ instance }}"
        name: "{{ ansible_hostname }}"
        ip_address: "{{ ansible_host }}"
        mac_address: '00:00:00:00:00:00'
        environment: test
        other:
          sys_class_name: cmdb_ci_linux_server
      register: _configuration_item

    - name: Debug Configuration item
      debug:
        var: _configuration_item

