---
- name: Automate Service Now 
  hosts: linux
  connection: local
  gather_facts: yes
  vars:
    node_info: []
  tasks:
    - name: Include variables
      include_vars: main.yml

    - name: Create Configuration item
      servicenow.itsm.configuration_item:
        instance: "{{ instance }}"
        name: "{{ ansible_hostname }}"
        ip_address: "{{ ansible_host }}"
        mac_address: '00:00:00:00:00:00'
        environment: test
        other:
          sys_class_name: cmdb_ci_linux_server
      register: _configuration_item

    - name: Debug Configuration item
      debug:
        var: _configuration_item

