---
- name: get node facts for SNOW
  hosts: all
  vars:
    node_info: []

  tasks:
  - name: Include variables
    include_vars: main.yml

  - name: Collect inventory facts
    ansible.builtin.set_stats:
      data:
        node_info: "{{ node_info + [{'hostname': ansible_facts['nodename'], 'default_ip': ansible_facts['default_ipv4']['address'], 'default_mac': ansible_facts['default_ipv4']['macaddress'], 'vendor': ansible_facts['product_name'] }] }}"

  - name: Set facts
    set_fact:
      node_info: node_info


- name: Automate SNOW 
  hosts: localhost
  connection: local
  tasks:
  - name: Include variables
    include_vars: main.yml

  - name: Debug
    debug:
      var: hostvars

  - name: Create/update configuration item
    servicenow.itsm.configuration_item:
      name: "{{ hostvars[item].node_info.hostname }}"
      ip_address: "{{ hostvars[item].node_info.default_ip }}"
      mac_address: "{{ hostvars[item].node_info.default_mac }}"
      environment: test
      other:
        sys_class_name: cmdb_ci_linux_server
    loop: "{{ hostvars | list }}"
    register: configuration_item

